version: "3.9"

services:
  web:
    build: .
    command: gunicorn core.wsgi:application -b 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static
      - db_volume:/app/db/
    ports:
      - "8000:8000"
    environment:
      - SQLITE_DATABASE=/app/db/db.sqlite3

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db_volume:
  static_volume:
