# Generated by Django 5.0.6 on 2024-06-17 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_cut_mark_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admission_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 17, 13, 5, 50, 603037)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2024, 6, 17, 13, 6, 46, 212477)),
            preserve_default=False,
        ),
    ]
