# Generated by Django 5.0.6 on 2024-06-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_admission_date_patient_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
