# Generated by Django 5.0.6 on 2024-06-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('name_of_local_guardian', models.CharField(max_length=100)),
                ('address_of_local_guardian', models.TextField()),
                ('name_of_person_responsible_for_treatment', models.CharField(max_length=100)),
                ('address_2', models.CharField(max_length=100)),
                ('detail_of_id_proof_recieved', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
