# Generated by Django 5.0.6 on 2024-06-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_representative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Declaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbal_abuse', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], help_text='Verbal abuse towards other', max_length=10)),
                ('physical_abuse', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], help_text='Physical abuse towards others', max_length=10)),
                ('breaking_articles', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], help_text='Breaking articles', max_length=10)),
                ('antisocial_activities', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], help_text='Involvement in antisocial activities', max_length=10)),
                ('law_suits', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], help_text='Pending law suit including complaint and grievancelodged under any authority against the patient', max_length=10)),
                ('abnormal_tendencies', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], help_text='Have you seen any depression, social isolation, self-harm or suicidal tendency within last 30 days in the patient', max_length=10)),
                ('abnormal_romatic_involment', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], help_text='Any abnormality during intimate romantic involvement', max_length=10)),
                ('high_risk_behavior', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], help_text='Exposure to high risk behavior', max_length=10)),
                ('unreasonable_anger', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], help_text='Unreasonable anger outburst', max_length=10)),
                ('irresponsible_aspects', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], help_text='Irresponsible toward life and familial aspects', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
