# Generated by Django 5.0.6 on 2024-06-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_remove_representative_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaration',
            name='abnormal_romatic_involment',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default=None, help_text='Any abnormality during intimate romantic involvement', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='abnormal_tendencies',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default=None, help_text='Have you seen any depression, social isolation, self-harm or suicidal tendency within last 30 days in the patient', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='antisocial_activities',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default=None, help_text='Involvement in antisocial activities', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='breaking_articles',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default=None, help_text='Breaking articles', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='high_risk_behavior',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default=None, help_text='Exposure to high risk behavior', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='irresponsible_aspects',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default=None, help_text='Irresponsible toward life and familial aspects', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='law_suits',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default=None, help_text='Pending law suit including complaint and grievancelodged under any authority against the patient', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='physical_abuse',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default=None, help_text='Physical abuse towards others', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='unreasonable_anger',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default=None, help_text='Unreasonable anger outburst', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='verbal_abuse',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Not Sure', 'Not Sure')], default=None, help_text='Verbal abuse towards other', max_length=10, null=True),
        ),
    ]
