# Generated by Django 5.0.6 on 2024-06-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_declaration_abnormal_romatic_involment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mou',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='mou',
            name='guardian_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='behavioural_disfunctions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='prediagnosed_mental_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='psychological_disturbance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='substance_abuse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='vindictiveness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='representative',
            name='Relationship with Patient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
