# Generated by Django 5.0.6 on 2024-06-27 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_item_itemquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemquantity',
            name='item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemquantity',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemquantity',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
