# Generated by Django 5.0.6 on 2024-06-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_alter_itemquantity_item_itemquantity_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='Cut Mark Details',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Date of Admission',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Date of Birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Date of Release',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Details of ID Proof Recieved',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Email Address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Income Per Month',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Language(s) Spoken',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Marital Status',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Name of Father',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Name of Mother',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Name of Patient',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Occupation',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Phone Number (1)',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Phone Number (2)',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Qualification',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Religion',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='Whatsapp Number',
        ),
        migrations.AddField(
            model_name='patient',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Admission'),
        ),
        migrations.AddField(
            model_name='patient',
            name='cut_mark_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cut Mark Details'),
        ),
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='patient',
            name='details_of_id_proof_recieved',
            field=models.TextField(blank=True, null=True, verbose_name='Details of ID Proof Recieved'),
        ),
        migrations.AddField(
            model_name='patient',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='father_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Father'),
        ),
        migrations.AddField(
            model_name='patient',
            name='income_pm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Income Per Month'),
        ),
        migrations.AddField(
            model_name='patient',
            name='language_spoken',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Language(s) Spoken'),
        ),
        migrations.AddField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], max_length=50, null=True, verbose_name='Marital Status'),
        ),
        migrations.AddField(
            model_name='patient',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Mother'),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='abinash', max_length=100, verbose_name='Name of Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number_1',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Phone Number (1)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number_2',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Phone Number (2)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Release'),
        ),
        migrations.AddField(
            model_name='patient',
            name='whatsapp_number',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='Whatsapp Number'),
        ),
        migrations.AddField(
            model_name='patient',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AddField(
            model_name='patient',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Qualification'),
        ),
        migrations.AddField(
            model_name='patient',
            name='religion',
            field=models.CharField(blank=True, choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Religion'),
        ),
    ]
