# Generated by Django 5.0.6 on 2024-06-28 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_remove_representative_address_of_local_guardian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFindings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaints', models.TextField(blank=True, null=True, verbose_name='Chief Complaints')),
                ('frame_of_reference', models.TextField(blank=True, null=True, verbose_name='Frame of Reference')),
                ('learning_disability_findings', models.TextField(blank=True, null=True, verbose_name='Learning Disability Findings')),
                ('relevant_history_childhood_findings', models.TextField(blank=True, null=True, verbose_name='Relevant History and Childhood Findings')),
                ('depression_anxiety_findings', models.TextField(blank=True, null=True, verbose_name='Depression & Anxiety Findings')),
                ('findings_on_needle_condom_awareness', models.TextField(blank=True, null=True, verbose_name='Findings on Needle and Condom Awareness')),
                ('findings_over_trauma', models.TextField(blank=True, null=True, verbose_name='Findings over Trauma')),
                ('aspects_traits_of_personality', models.TextField(blank=True, null=True, verbose_name='Aspects and Traits of Personality')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Summary')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
