# Generated by Django 5.0.6 on 2024-06-29 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0018_reportfindings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_taking_over', models.DateField(blank=True, null=True, verbose_name='Date of Taking Over')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_return', models.DateField(blank=True, null=True, verbose_name='Date of Return')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
