# Generated by Django 5.0.6 on 2024-06-30 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_temporaryrelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudicialProceedings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_hearing', models.DateField(blank=True, null=True, verbose_name='Date of Hearing')),
                ('case_no', models.CharField(blank=True, max_length=255, null=True)),
                ('allowed_to_attend', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255, null=True, verbose_name='Allowed to Attend')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
