# Generated by Django 5.0.6 on 2024-07-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_judicialproceedings'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='uuid',
            field=models.CharField(default=2024, max_length=10),
            preserve_default=False,
        ),
    ]
