# Generated by Django 5.0.6 on 2024-07-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_patient_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mou',
            name='lab_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='monthly_fee_first_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='monthly_fee_second_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='monthly_fee_third_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='uuid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
